name: Date
on: 
  push:
    branches: [ master ]
jobs:
    build:
       runs-on: ubuntu-lastest
       permissions:
         contents: write
       
       steps: 
              - name: Checkout
                uses: actions/checkout@v4

              - name: Setup python
                uses: actions/setup-python@v5
                with:
                  python-version: '3.11'

              - name: Run archive
                run: python date.py

              - name: Upload generated file
                uses: stefanzweifel/git-auto-commit-action@v5
                with:
                  commit_message: update date 
                  
               

       
       
