name: Run Python Script

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Run Python script
      run: python date.py

  

    - name: Commit changes
      run: |
        git add fecha_hora.txt
        git commit -m "Add generated fecha_hora.txt"

    - name: Push changes
      run: |
        git push origin HEAD: master

     

